# Generated by Django 5.2.12 on 2026-03-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='role_permission',
            new_name='read_permission',
        ),
    ]
