# Generated by Django 5.2.12 on 2026-03-05 13:32

from django.db import migrations


def seed_data(app,schema_editor):
    Role = app.get_model('authentication', 'Role')
    BusinessElement = app.get_model('authentication', 'BusinessElement')
    AccessRoleRule = app.get_model('authentication', 'AccessRoleRule')

    admin_role, _ = Role.objects.get_or_create(name='admin')
    user_role, _ = Role.objects.get_or_create(name='user')

    orders, _ = BusinessElement.objects.get_or_create(name='orders')
    products, _ = BusinessElement.objects.get_or_create(name='products')
    reports, _ = BusinessElement.objects.get_or_create(name='reports')

    AccessRoleRule.objects.get_or_create(role=admin_role, element=orders, defaults=dict(
        read_permission=True, read_all_permission=True, create_permission=True, update_permission=True,
        update_all_permission=True, delete_permission=True, delete_all_permission=True,
        ),
    )

    AccessRoleRule.objects.get_or_create(role=user_role, element=products, defaults=dict(
        read_permission=True, read_all_permission=True, create_permission=True,
        ),
    )

    AccessRoleRule.objects.get_or_create(role=admin_role, element=reports, defaults=dict(
        read_permission=True, read_all_permission=True,
        ),
    )

    AccessRoleRule.objects.get_or_create(role=user_role, element=orders, defaults=dict(read_permission=True,),)

    AccessRoleRule.objects.get_or_create(role=user_role, element=products, defaults=dict(read_permission=True,),)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
