# Generated by Django 5.2.12 on 2026-03-05 14:40

from django.db import migrations


def seed_business_elements(app, schema_editor):
    BusinessElement = app.get_model('authentication', 'BusinessElement')

    elements = ['orders', 'products', 'reports']

    for e in elements:
        BusinessElement.objects.get_or_create(name=e)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_seed_rbac'),
    ]

    operations = [
        migrations.RunPython(seed_business_elements),
    ]
